[tools]
node = "26.3.1"

[settings]
# Tells mise to officially respect .nvmrc and .node-version files
idiomatic_version_file_enable_tools = ["node"]
experimental = true
pin = true

[tasks.deps]
run = "npm install"
description = "Installs dependencies"

[tasks.astro]
run = "npm run dev"
description = "Starts the development server"

[tasks.wrangler]
run = "wrangler pages dev dist"
description = "Starts the wrangler dev server"

[tasks.dev]
run = { tasks = [ "astro", "wrangler" ] }
description = "Starts the development server along with the wrangler task"

[tasks.copy-functions]
run =  "cp -R functions dist/functions 2>/dev/null; true"
description = "Copies the functions folder to the dist folder"

[tasks.build]
run = "npm run build"
description = "Builds the project with npm"

# Run using `mise r preview`
[tasks.preview]
run = [ { task = "build" }, { task = "copy-functions" }, { task = "wrangler" } ]
description = "Starts the preview server using astro's inbuilt preview along with the wrangler server"
