/*
 * Generated by @gcoredev/FastEdge-sdk-js fastedge-init
 */

import { createStaticServer } from "@gcoredev/fastedge-sdk-js";
import { staticAssetManifest } from "./build/static-asset-manifest.js";
import { serverConfig } from "./build-config.js";

const staticServer = createStaticServer(staticAssetManifest, serverConfig);

async function handleRequest(event) {
  const response = await staticServer.serveRequest(event.request);
  if (response != null) {
    return response;
  }

  return new Response("Not found", { status: 404 });
}

addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
